apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
        - name: todo-ui
          image: acrdigwimicrotodoappdev.azurecr.io/todo-ui:v2
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_GET_TASKS_API_BASE_URL
              value: "http://get.digwi.online"

            - name: REACT_APP_DELETE_TASK_API_BASE_URL
              value: "http://delete.digwi.online"

            - name: REACT_APP_CREATE_TASK_API_BASE_URL
              value: "http://add.digwi.online"
